# TODO:
#  A. Depending on order of definition/calculation, may be possible to simply set numFrameStyles based on
#     len(HypnicGUI.frames).
#    1. This would require storing a reference to the HypnicGUI instance as a member variable
#       within this StyleContainer class.
#    2. It would also increase the importance of ensuring that EVERY frame ends up in the HypnicGUI.frames list
#      a. Detrimental in some ways since this could lead to bugs
#      b. At the same time, could be good in serving as a visual indicator of whether some frames are missing
#         from the frames list (whether due to never having been added, or somehow having been manipulated erroneously)

__name__ = "style_container"

# Library Imports
import random
import tkinter
from tkinter import ttk

# Local Imports
import hypnic_helpers

# G L O B A L   V A R I A B L E S
# DEFAULT STYLE PARAMETERS
DEFAULT_BG_COLOR = ""


class StyleContainer():

    # Constructor has a gui_ parameter which is saved in self.gui in order to access the HypnicGUI members
    def __init__(self, gui_):

        # So that the StyleContainer instance can refer to the HypnicGUI instance
        self.gui = gui_

        # TODO: Remove this block comment; it's a relic from when DimensionContainer was initialized within this class
        """
        # This class holds the DimensionContainer object instance, "dims",
        # in order to access things like padding specification variables. It is initialized here
        self.dims = dimension_container.DimensionContainer(self.gui)
        """

        # This class also holds the ttk Style object, which can be referenced from the HypnicGUI instance if needed
        self.ttkStyleObj = ttk.Style()
        # Sets the ttk theme
        # TODO: Change this, I'm only making it Win-XP because I think that'll make it stand out whether it's having an effect
        #print(self.ttkStyleObj.theme_names())
        #print(self.ttkStyleObj.theme_use())
        self.ttkStyleObj.theme_use("xpnative")

        # A list of strings which are the names of custom styles
        # Any time a custom style is defined with the ttk.style.map() method, it should be stored
        self.styles = []
        # A list of strings which specifically refer to ttk Frame-related styles
        self.frameStyles = []
        # A list of strings which specifically refer to ttk Label-related styles
        self.labelStyles = []
        # A list of strings which specifically refer to styles for ttk Labels with an associated image
        self.imageLabelStyles = []
        # A list of strings which specifically refer to styles for ttk BUTTON widgets
        self.buttonStyles = []
        # A list of strings which specifically refer to styles for ttk Labels with associated text
        self.textLabelStyles = []
        # A list of strings which specifically refer to styles for ttk Labels with associated textvariable values
        self.textvariableLabelStyles = []

        # Defines and configures the GUI's ttk styles
        self.ttkStyleConfig()

    def ttkStyleConfig(self):
        # D E F A U L T     S T Y L E S
        # These styles will apply to all relevant ttk widgets which are not given a custom style
        # TButton represents the default ttk Button (the class name for ttk::button is TButton)
        self.ttkStyleObj.configure("TButton",
                                   padding=self.gui.dims.internalPaddingButton,
                                   relief="flat",
                                   background="#555")
        # TFrame : ttk.Frame
        self.ttkStyleObj.configure("TFrame",
                                   background="#16B")
        # TLabelFrame : ttk.labelFrame
        self.ttkStyleObj.configure("TLabelFrame",
                                   background="#5AF")
        # TLabel : ttk.label
        self.ttkStyleObj.configure("TLabel",
                                   background="#9D3")

        # C U S T O M     S T Y L E S

        # FRAME STYLES
        # Creates an assortment of Frame styles with random background colors to keep grid elements visually distinct
        # Number of random ttk Frame styles to generate
        # TODO: Define this elsewhere, and based on hard-coded parameters
        numFrameStyles = 50
        for i in range(numFrameStyles):
            # styleName values are "fs0.TFrame", "fs1.TFrame", etc
            styleName = ("fs" + str(i) + ".TFrame")
            # Configures a style object, with key styleName, using different colors generated by hypnic_helpers.py
            # Frames are colored differently to make them more easily distinguished
            if i % 5 == 0:
                self.ttkStyleObj.configure(styleName, background=hypnic_helpers.rgbToHex(hypnic_helpers.getRandomRed()))
            if i % 5 == 1:
                self.ttkStyleObj.configure(styleName, background=hypnic_helpers.rgbToHex(hypnic_helpers.getRandomGray()))
            if i % 5 == 2:
                self.ttkStyleObj.configure(styleName, background=hypnic_helpers.rgbToHex(hypnic_helpers.getRandomPurple()))
            if i % 5 == 3:
                self.ttkStyleObj.configure(styleName, background=hypnic_helpers.rgbToHex(hypnic_helpers.getRandomGreen()))
            if i % 5 == 4:
                self.ttkStyleObj.configure(styleName, background=hypnic_helpers.rgbToHex(hypnic_helpers.getRandomBlue()))

            # Adds styleName to self.frameStyles for future reference
            self.frameStyles.append(styleName)

        # COMBOBOX STYLES
        # TODO: Custom combobox style to save space when dealing with single-character Comboboxes
        self.ttkStyleObj.configure("singleChar.TCombobox")

    # SET / GET METHODS
    # Good practice for use when modifying StyleContainer variables from externally (like from the HypnicGUI instance)
    # Also good for clarity when pulling/calculating values from here to the GUI instance

    # Returns a random element from self.styles
    def getRandomStyle(self):
        return self.styles[random.randrange(0, len(self.styles))]

    # Returns a random element from self.frameStyles
    def getRandomFrameStyle(self):
        return self.frameStyles[random.randrange(0, len(self.frameStyles))]

    # Returns a random element from self.labelStyles
    def getRandomLabelStyle(self):
        return self.labelStyles[random.randrange(0, len(self.labelStyles))]

    # Returns a random element from self.buttonStyles
    def getRandomButtonStyle(self):
        return self.buttonStyles[random.randrange(0, len(self.buttonStyles))]

    # Returns a random element from self.imageLabelStyles
    def getRandomImageLabelStyle(self):
        return self.imageLabelStyles[random.randrange(0, len(self.imageLabelStyles))]

    # Returns a random element from self.textLabelStyles
    def getRandomTextLabelStyle(self):
        return self.textLabelStyles[random.randrange(0, len(self.textLabelStyles))]

    # Returns a random element from self.taxtvariableLabelStyles
    def getRandomTextvariableLabelStyle(self):
        return self.textvariableLabelStyles[random.randrange(0, len(self.textvariableLabelStyles))]